Capstone Project

Supply Chain Analytics: Inventory Management, Logistics Optimization, and Demand Forecasting

Link: https://github.com/eyowhite/Messy-dataset/blob/main/warehouse_messy_data.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from google.colab import files
uploaded=files.upload()

Saving warehouse_messy_data.csv to warehouse_messy_data.csv

In [3]:
df=pd.read_csv("warehouse_messy_data.csv")

In [4]:
df.head()

/usr/local/lib/python3.13/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300,9.99,Supplier C,In Stock,NaN
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,two hundred,19.99,Supplier C,Out of Stock,NaN
2,1860,widget a,CLOTHING,Warehouse 2,Aisle 3,100,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
4,1106,widget a,FURNITURE,Warehouse 3,Aisle 3,two hundred,9.99,Supplier D,Out of Stock,25/04/2023

In [5]:
df.tail()

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
995,1009,widget b,FURNITURE,Warehouse 2,Aisle 2,100,NaN,Supplier C,In Stock,15/01/2023
996,1823,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,300,19.99,Supplier B,In Stock,20/12/2022
997,1797,gadget z,TOYS,Warehouse 3,Aisle 5,150,9.99,Supplier C,Low Stock,05/03/2023
998,1241,widget c,FURNITURE,Warehouse 2,Aisle 2,100,49.99,Supplier C,Low Stock,20/12/2022
999,1250,widget a,CLOTHING,Warehouse 1,Aisle 3,100,49.99,Supplier B,Out of Stock,20/12/2022

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product ID      1000 non-null   int64
 1   Product Name    1000 non-null   object
 2   Category        1000 non-null   object
 3   Warehouse       1000 non-null   object
 4   Location        1000 non-null   object
 5   Quantity        842 non-null    object
 6   Price           793 non-null    float64
 7   Supplier        1000 non-null   object
 8   Status          1000 non-null   object
 9   Last Restocked  800 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 78.3+ KB

In [7]:
df.describe()

        Product ID       Price
count  1000.000000  793.000000
mean   1503.929000   28.085839
std     289.998108   14.686312
min    1000.000000    9.990000
25%    1242.750000   19.990000
50%    1505.000000   29.990000
75%    1757.250000   49.990000
max    1998.000000   49.990000

In [8]:
df.describe(include="object")

,Product Name,Category,Warehouse,Location,Quantity,Supplier,Status,Last Restocked
count,1000,1000,1000,1000,842,1000,1000,800
unique,6,4,3,5,5,4,3,4
top,gadget y,FURNITURE,Warehouse 1,Aisle 3,300,Supplier B,In Stock,20/12/2022
freq,177,265,349,211,177,288,340,218